# Generated by Django 2.2.7 on 2019-11-15 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='CreatedDate',
            field=models.DateField(default=0.00036321611358758457),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='Deadline',
            field=models.DateField(default=0.00036321611358758457),
            preserve_default=False,
        ),
    ]
