# Generated by Django 2.2.7 on 2019-11-15 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191115_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='CreatedDate',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Deadline',
        ),
    ]
